[package]
name = "wasm-chip8"
version = "1.0.0"
authors = ["Masato Bito <m@btmst.jp>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "~0.4.11"
#log4rs = "~0.13.0"
rand = "~0.7.3"
#termion = "~1.5.5"
wasm-bindgen = "*"
